/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    ButtonSection: typeof import('./src/components/guide/ButtonSection.vue')['default']
    ComponentSection: typeof import('./src/components/guide/ComponentSection.vue')['default']
    LazyComponent: typeof import('./src/components/common/LazyComponent.vue')['default']
    MusicGrid: typeof import('./src/components/music/MusicGrid.vue')['default']
    MusicHeader: typeof import('./src/components/music/MusicHeader.vue')['default']
    MusicPlayer: typeof import('./src/components/music/MusicPlayer.vue')['default']
    MusicSearch: typeof import('./src/components/music/MusicSearch.vue')['default']
    MusicSidebar: typeof import('./src/components/music/MusicSidebar.vue')['default']
    NotificationToast: typeof import('./src/components/NotificationToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAccordion: typeof import('./src/components/ui/molecules/VAccordion.vue')['default']
    VAdminLayout: typeof import('./src/components/ui/templates/VAdminLayout.vue')['default']
    VAlert: typeof import('./src/components/ui/atoms/VAlert.vue')['default']
    VAvatar: typeof import('./src/components/ui/atoms/VAvatar.vue')['default']
    VBadge: typeof import('./src/components/ui/atoms/VBadge.vue')['default']
    VButton: typeof import('./src/components/ui/atoms/VButton.vue')['default']
    VCard: typeof import('./src/components/ui/atoms/VCard.vue')['default']
    VCheckbox: typeof import('./src/components/ui/atoms/VCheckbox.vue')['default']
    VChip: typeof import('./src/components/ui/atoms/VChip.vue')['default']
    VDashboardLayout: typeof import('./src/components/ui/templates/VDashboardLayout.vue')['default']
    VDataTable: typeof import('./src/components/ui/molecules/VDataTable.vue')['default']
    VFooter: typeof import('./src/components/ui/organisms/VFooter.vue')['default']
    VForm: typeof import('./src/components/ui/molecules/VForm.vue')['default']
    VFormField: typeof import('./src/components/ui/molecules/VFormField.vue')['default']
    VHeader: typeof import('./src/components/ui/organisms/VHeader.vue')['default']
    VibeHeader: typeof import('./src/components/vibe/VibeHeader.vue')['default']
    VibePlayer: typeof import('./src/components/vibe/VibePlayer.vue')['default']
    VibeSidebar: typeof import('./src/components/vibe/VibeSidebar.vue')['default']
    VIcon: typeof import('./src/components/ui/atoms/VIcon.vue')['default']
    VInput: typeof import('./src/components/ui/atoms/VInput.vue')['default']
    VLandingLayout: typeof import('./src/components/ui/templates/VLandingLayout.vue')['default']
    VLayout: typeof import('./src/components/ui/templates/VLayout.vue')['default']
    VMenu: typeof import('./src/components/ui/molecules/VMenu.vue')['default']
    VModal: typeof import('./src/components/ui/molecules/VModal.vue')['default']
    VNavigation: typeof import('./src/components/ui/molecules/VNavigation.vue')['default']
    VPage: typeof import('./src/components/ui/templates/VPage.vue')['default']
    VProgress: typeof import('./src/components/ui/atoms/VProgress.vue')['default']
    VRadio: typeof import('./src/components/ui/atoms/VRadio.vue')['default']
    VSelect: typeof import('./src/components/ui/atoms/VSelect.vue')['default']
    VSidebar: typeof import('./src/components/ui/organisms/VSidebar.vue')['default']
    VStepper: typeof import('./src/components/ui/molecules/VStepper.vue')['default']
    VSwitch: typeof import('./src/components/ui/atoms/VSwitch.vue')['default']
    VTabs: typeof import('./src/components/ui/molecules/VTabs.vue')['default']
    VTextarea: typeof import('./src/components/ui/atoms/VTextarea.vue')['default']
    VTooltip: typeof import('./src/components/ui/molecules/VTooltip.vue')['default']
  }
}
